name: .NET Core

on:
  push:
    branches: [ net5 ]
  pull_request:
    branches: [ net5 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.8.20417.9'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj
    - name: Publish
      run: dotnet publish --no-restore --verbosity normal src/OrchardCore.Cms.Web/OrchardCore.Cms.Web.csproj
